colorscheme slate
filetype plugin indent on
syntax enable

set background=dark
set colorcolumn=110
set mouse=a
set compatible

set ignorecase
set incsearch
set list

set nobackup
set nohlsearch
set noswapfile

set nu
set number
set relativenumber

set smartcase
set smartindent

set laststatus=2
set tabstop=2
set shiftwidth=2
set expandtab
