colorscheme default
hi SpecialKey ctermbg=black ctermfg=red guibg=black guifg=red
set colorcolumn=110
set expandtab
set ignorecase
set laststatus=2
set list
set listchars=tab:»\ ,trail:•
set mouse=a
set nobackup
set nohlsearch
set noswapfile
set nu
set relativenumber
set shiftwidth=2
set smartcase
set smartindent
set tabstop=2
