default: nvim

exec:
  sxiv:
    [jpg, jpeg, png, gif, svg, webp]
  zathura:
    [pdf, djvu, epub, ps]

syntax_highlight: true

default_theme: SolarizedDark

color:
  dir_fg: LightCyan
  file_fg: LightWhite
  symlink_fg: LightYellow
