#!/usr/bin/env bash

[[ -f $HOME/.profile ]] && source $HOME/.profile

bspc rule -r *:*

[[ -f $HOME/.local/bin/start-bspwm ]] && $HOME/.local/bin/start-bspwm &
[[ -f $HOME/.local/bin/mon-conf ]] && $HOME/.local/bin/mon-conf &
[[ -f $HOME/.config/polybar/launch.sh ]] && $HOME/.config/polybar/launch.sh --forest &

bspc config border_width        2
bspc config window_gap          12

bspc config split_ratio          0.50
bspc config borderless_monocle   true
bspc config gapless_monocle      true
