#!/bin/sh

local=`ip -4 addr | grep "global dynamic" | awk '{print $2}' | sed "s/\/.*//g"`
ipv4=`wget http://ipinfo.io/ip -qO -`
ipv6=`ip -6 addr | grep "global" | sed 1q | awk '{print $2}' | sed "s/\/.*//g"`

echo "local : $local | IPv4 : $ipv4 | IPv6 : $ipv6"
