#!/bin/sh

local=`ip -4 addr | grep "global dynamic" | awk '{print $2}' | sed "s/\/.*//g"`
iface=`route | grep default | awk '{print $8}'`

if [ -z $local ] || [ -z $iface ]
then
	echo '\e[31mnetwork down'
else
	echo "\e[0m$iface : $local"
fi
