#!/bin/bash

# Output locations
ranger_shortcuts="$HOME/.config/ranger/shortcuts.conf"

# Remove, prepare files
rm -f "$ranger_shortcuts"

# Format the `bmdirs` file in the correct syntax and sent it to all three configs.
sed "s/\s*#.*$//;/^\s*$/d" "$HOME/.config/.dirs" | tee >(awk '{print "alias "$1"=\"cd "$2" && ls -lArth\" \\"}') | awk '{print "map g"$1" cd "$2"\nmap t"$1" tab_new "$2"\nmap m"$1" shell mv -v %s "$2"\nmap Y"$1" shell cp -rv %s "$2}' >> "$ranger_shortcuts"

# Format the `configs` file in the correct syntax and sent it to both configs.
sed "s/\s*#.*$//;/^\s*$/d"  "$HOME/.config/.files" | tee >(awk '{print "alias "$1"=\"$EDITOR "$2"\" \\"}') | awk '{print "map "$1" shell $EDITOR "$2}' >> "$ranger_shortcuts"
